
module.exports = {
  Departement: require('./Departement'),
  District: require('./district'),
  Localite: require('./Localite'),
  Menage: require('./Menage'),
  Nationalite: require('./Nationalite'),
  NiveauScolaire: require('./NiveauScolaire'),
  Option: require('./Option'),
  Parcelle: require('./Parcelle'),
  Pays: require('./Pays'),
  Piece: require('./Piece'),
  Producteur: require('./Producteur'),
  Profession: require('./Profession'),
  Profile: require('./Profile'),
  Region: require('./Region'),
  SecteurAdministratif: require('./SecteurAdministratif'),
  Souspref: require('./Souspref'),
  User: require('./User'),
  Village: require('./Village'),
  Zonedenombre: require('./Zonedenombre'),
  Zone_interdit: require('./Zone_interdit'),
};
