
module.exports = {
  Questionnaire: require('./Questionnaire'),
  Volet: require('./Volet'),
  Section: require('./Section'),
  Question: require('./Question'),
  Reponse: require('./Reponse'),
  Interview: require('./Interview'),
  Departement: require('./Departement'),
  District: require('./district'),
  Pays: require('./Pays'),
  Souspref: require('./Souspref'),
  Region: require('./Region'),
  Zone_interdit: require('./Zone_interdit'),
  Village: require('./Village'),
  Menu: require('./Menu'),
  Profile: require('./Profile'),
  User: require('./User'),
  Nationalite: require('./Nationalite'),
  NiveauScolaire: require('./NiveauScolaire'),
  Piece: require('./Piece'),
  Parcelle: require('./Parcelle'),
  Producteur: require('./Producteur'),
  OptionSchema: require('./Option'),
};
